### ISSUE TITLE
讨论一下实现思路

### ISSUE THREAD

**Issue by mayneyao** [sorcererxw/blog#13]
我最近也在基于notion搞blog。现在还是手动挡，导出md ->gatsby渲染成静态页面 

看兄弟你的实现，是打算把block都解析一遍嘛，组件一一对应？

**Comment by sorcererxw** [comment]
是的，通过Notion接口实时拉取数据展示
可以看看 https://blog.sorcererxw.com/post/build-blog-with-notion
