### ISSUE TITLE
Long text getting cut off | 长文被切断了

### ISSUE THREAD

**Issue by perper29** [sorcererxw/blog#23]
Long text is not rendering on the blog page.

What is the fix for this?

I tried about 6000 words of text and it is not rendering. Only parts of it renders

---------------------------------------------------------------------------------
长文本未在博客页面上呈现。

有什么办法解决这个问题？

我尝试了大约6000个单词的文字而且它没有渲染。只有部分呈现

**Comment by sorcererxw** [comment]
已修复，详情可查看此 commit

https://github.com/sorcererxw/blog/commit/cfa1232c352853e9135d46163affc940e041c680
